include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/injection/injection.config.dart'
  errors:
    missing_required_param: error

linter:
  rules:
    sort_constructors_first: true
    require_trailing_commas: true
    prefer_single_quotes: true
    always_use_package_imports: true
