name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: actually-colab/github-action-create-env-file@v2.3
        with:
          envkey_API_KEY: ${{ secrets.USER_ID }}
          envkey_USER_ID: ${{ secrets.API_KEY }}
          file_name: .env
          fail_on_empty: false