name: showcase_app

on: [push]

jobs:
  build:
    uses: alicja-ogonowska/very_good_workflows/tree/main/.github/workflows/flutter_package.yml
    with:
      flutter_channel: stable
      flutter_version: 3.0.4
